"""empty message

Revision ID: 4de36304d443
Revises: 4e9082c8c2a3
Create Date: 2023-07-10 23:43:02.741033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de36304d443'
down_revision = '4e9082c8c2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('numG', sa.Integer(), nullable=True),
    sa.Column('numC', sa.Integer(), nullable=True),
    sa.Column('numR', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('team', sa.VARCHAR(length=100), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('numG', sa.INTEGER(), nullable=True),
    sa.Column('numC', sa.INTEGER(), nullable=True),
    sa.Column('numR', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('players_db')
    # ### end Alembic commands ###
