"""Adding column numR

Revision ID: 4e9082c8c2a3
Revises: 017d48994cc3
Create Date: 2023-07-10 23:37:38.867441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9082c8c2a3'
down_revision = '017d48994cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numR', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('numR')

    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('team', sa.VARCHAR(length=100), nullable=True),
    sa.Column('year', sa.VARCHAR(length=100), nullable=True),
    sa.Column('numR', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
